language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- ant run-tests
script:
- ant
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: tGlZhxo4nzJq/gJ4QVKvORQmoHUyRR6kHpIvhudBBlgbPLbRhR7nUE6rDkNUytCh7yqN8kn6zFZvrK3cM88PlQ6JNScgH/n0GbcbDw9BLqLnPUPz9xve2EBubrjEhlFFzb3K6nnlO/T48wSH9N/8U1tv03IuxmP5b/6DIYcmR9NVU8erJIbR/NuiGMadQ17kSXLyaRwPZkOb/SVW2grxgaBW/987E/p30i61wknlPq9Tp+MZuYHtH3ncufMO+IV3AVfE3lnpukW37lPghnYmnQVY6BxCJanG6mJW2VqO9wAT2iSpBh/l7gZB0wULv1+JNrfbLBz4poPcU2ZMjf8G2TNmw6SJ5K9iwCIkW+gGKA7LbgeznIavHtEQNH/gEka+KTNQyWLLwDGtKzwisgnrdJuLObOfUmv9pbPLFHPQXkm0wXnD+x8MxihFnrMM1iDknSF5qtCXsnZr+UoDS356d3dAba1eGlkKA4A/qZLV5bRPPGvDf5OzjKSkvmFAwwQllGkfqgawMAQi+mjf+4TgAXKmJH/dmK5uo9pAZ/YHYJ2pA9whZkmDQKqA0rUCVuhc9PdZeF0OJkFYKr4mwWP5osbnLLrHoUgIRYj3Z80M+x8wD4kG6lO0IIq36YGpzSPQb4bo5u4BuuvmGM/Z8hMG0Ca7oCN61cm3QAacXq7bcmg=
  email: false
